services:
  - type: web
    name: ai-audio-classifier
    env: python
    buildCommand: cd Code && pip install -r requirements.txt
    startCommand: cd Code && gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
    autoDeploy: true
